version: "3.3"

services:
  nginx:
    image: nginx:1.17.8
    container_name: server
    ports:
      - "80:80"
    volumes:
      - ./config:/etc/nginx/conf.d
      - ./server:/var/www
    links:
      - app
  app:
    build: "./server"
    container_name: app
    ports:
      - "9000:9000"
    volumes:
      - ./server/:/var/www